# Generated by Django 4.0.5 on 2025-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_employee_phone_number_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='ems.job', verbose_name='Trabajos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Nombre del trabajo'),
        ),
    ]
